name: wabi_sabi_app
description: A new Flutter application.


publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  freezed_annotation: ^0.14.1
  dartz: ^0.10.0-nullsafety.1
  flutter_bloc: ^7.0.0
  firebase_core: ^1.2.0
  google_sign_in: ^5.0.4
  firebase_auth: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.1
  freezed: ^0.14.1+3

flutter:

  uses-material-design: true

